# When modifying this file, please validate using
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate
comment: false
coverage:
  status:
    patch: off
    # https://github.com/openscanhub/openscanhub/issues/136#issuecomment-1766096310
    # Unit tests usually finish first and have a coverage of above 40%.
    # Avoid CI failures if overall coverage stays above 40%.
    project:
      default:
        target: 40%
