--
-- This file is generated by migra: https://github.com/djrobstep/migra
-- The command is: migra --unsafe postgresql://<user>:<pass>@<original_db_host>/<db_name> postgresql://<user>:<pass>@<new_db_host>/<db_name>
--
-- We need this because the current production database is so old that there are
-- new records about applied migrations. This script transfers the old production
-- database to the state how an empty database created by all migrations we have in
-- the project looks like.
--
-- When we deploy our new version to production and run this script for the first time,
-- we can remove it. The database will then know about migration and all subsequent changes
-- will be managed by migrations in the standard way.
--

create sequence "public"."django_migrations_id_seq";

create sequence "public"."xmlrpc_xmlrpclog_id_seq";

alter table "public"."auth_group_permissions" drop constraint "auth_group_permissions_group_id_key";

alter table "public"."auth_group_permissions" drop constraint "auth_group_permissions_permission_id_fkey";

alter table "public"."auth_group_permissions" drop constraint "group_id_refs_id_3cea63fe";

alter table "public"."auth_message" drop constraint "auth_message_user_id_fkey";

alter table "public"."auth_permission" drop constraint "auth_permission_content_type_id_key";

alter table "public"."auth_permission" drop constraint "content_type_id_refs_id_728de91f";

alter table "public"."auth_user_groups" drop constraint "auth_user_groups_group_id_fkey";

alter table "public"."auth_user_groups" drop constraint "auth_user_groups_user_id_key";

alter table "public"."auth_user_groups" drop constraint "user_id_refs_id_831107f1";

alter table "public"."auth_user_user_permissions" drop constraint "auth_user_user_permissions_permission_id_fkey";

alter table "public"."auth_user_user_permissions" drop constraint "auth_user_user_permissions_user_id_key";

alter table "public"."auth_user_user_permissions" drop constraint "user_id_refs_id_f2045483";

alter table "public"."django_admin_log" drop constraint "django_admin_log_content_type_id_fkey";

alter table "public"."django_admin_log" drop constraint "django_admin_log_user_id_fkey";

alter table "public"."django_content_type" drop constraint "django_content_type_app_label_key";

alter table "public"."errata_capability_analyzers" drop constraint "analyzer_id_refs_id_734f3fc6e20622f7";

alter table "public"."errata_capability_analyzers" drop constraint "capability_id_refs_id_a2333ded1f921a5";

alter table "public"."errata_capability_analyzers" drop constraint "errata_capability_analyzers_capability_id_23cc0d877f2d97b9_uniq";

alter table "public"."errata_capability_caps" drop constraint "capability_id_refs_id_504185f5267538e6";

alter table "public"."errata_capability_caps" drop constraint "errata_capability_caps_capability_id_79a5de5125845a77_uniq";

alter table "public"."errata_capability_caps" drop constraint "packagecapability_id_refs_id_61845e489b485bd7";

alter table "public"."errata_scanningsession" drop constraint "profile_id_refs_id_5116157a20f803b5";

alter table "public"."errata_scanningsession_caps" drop constraint "capability_id_refs_id_4bc6a54e62921fe8";

alter table "public"."errata_scanningsession_caps" drop constraint "errata_scanningsession__scanningsession_id_ed60a3efd776a42_uniq";

alter table "public"."errata_scanningsession_caps" drop constraint "scanningsession_id_refs_id_339737c5ce4a78ea";

alter table "public"."hub_task" drop constraint "hub_task_arch_id_fkey";

alter table "public"."hub_task" drop constraint "hub_task_channel_id_fkey";

alter table "public"."hub_task" drop constraint "hub_task_owner_id_fkey";

alter table "public"."hub_task" drop constraint "hub_task_resubmitted_by_id_fkey";

alter table "public"."hub_task" drop constraint "hub_task_worker_id_fkey";

alter table "public"."hub_task" drop constraint "parent_id_refs_id_42719ec3";

alter table "public"."hub_task" drop constraint "resubmitted_from_id_refs_id_42719ec3";

alter table "public"."hub_worker_arches" drop constraint "hub_worker_arches_arch_id_fkey";

alter table "public"."hub_worker_arches" drop constraint "hub_worker_arches_worker_id_key";

alter table "public"."hub_worker_arches" drop constraint "worker_id_refs_id_492bd327";

alter table "public"."hub_worker_channels" drop constraint "hub_worker_channels_channel_id_fkey";

alter table "public"."hub_worker_channels" drop constraint "hub_worker_channels_worker_id_key";

alter table "public"."hub_worker_channels" drop constraint "worker_id_refs_id_b7a47a49";

alter table "public"."scan_analyzerversion" drop constraint "analyzer_id_refs_id_447b32f9257b5674";

alter table "public"."scan_analyzerversion_mocks" drop constraint "analyzerversion_id_refs_id_4a36a35f5effc1bd";

alter table "public"."scan_analyzerversion_mocks" drop constraint "mockconfig_id_refs_id_4025e84b46123796";

alter table "public"."scan_analyzerversion_mocks" drop constraint "scan_analyzerversion_m_analyzerversion_id_6d8eeff244a5ca45_uniq";

alter table "public"."scan_clientanalyzer" drop constraint "analyzer_id_refs_id_7043b151689a7ff2";

alter table "public"."scan_etmapping" drop constraint "ck_state_pstv_48baed4aa7e731af";

alter table "public"."scan_etmapping" drop constraint "latest_run_id_refs_id_6c55f01a045a1870";

alter table "public"."scan_packageattribute" drop constraint "package_id_refs_id_7f5502ba21165d5e";

alter table "public"."scan_packageattribute" drop constraint "release_id_refs_id_30185b4cbc66b16";

alter table "public"."scan_packagecapability" drop constraint "package_id_refs_id_1bfa627e4b38b0d";

alter table "public"."scan_packagecapability" drop constraint "release_id_refs_id_5d89755183ae7915";

alter table "public"."scan_scan" drop constraint "base_id_refs_id_ff7b5cf5";

alter table "public"."scan_scan" drop constraint "parent_id_refs_id_ff7b5cf5";

alter table "public"."scan_scan" drop constraint "scan_scan_package_id_fkey";

alter table "public"."scan_scan" drop constraint "scan_scan_tag_id_fkey";

alter table "public"."scan_scan" drop constraint "username_id_refs_id_1bd0a5a413309e84";

alter table "public"."scan_scanbinding" drop constraint "result_id_refs_id_65a2a1d6";

alter table "public"."scan_scanbinding" drop constraint "scan_scanbinding_scan_id_fkey";

alter table "public"."scan_scanbinding" drop constraint "scan_scanbinding_task_id_fkey";

alter table "public"."scan_systemrelease" drop constraint "parent_id_refs_id_7278de99";

alter table "public"."scan_tag" drop constraint "scan_tag_mock_id_fkey";

alter table "public"."scan_tag" drop constraint "scan_tag_release_id_fkey";

alter table "public"."scan_taskextension" drop constraint "task_id_refs_id_41dad7f83549d960";

alter table "public"."stats_statresults" drop constraint "stats_statresults_release_id_fkey";

alter table "public"."stats_statresults" drop constraint "stats_statresults_stat_id_fkey";

alter table "public"."upload_fileupload" drop constraint "upload_fileupload_owner_id_fkey";

alter table "public"."waiving_bugzilla" drop constraint "waiving_bugzilla_package_id_fkey";

alter table "public"."waiving_bugzilla" drop constraint "waiving_bugzilla_release_id_fkey";

alter table "public"."waiving_checker" drop constraint "waiving_checker_group_id_fkey";

alter table "public"."waiving_defect" drop constraint "checker_id_refs_id_b0d46444";

alter table "public"."waiving_defect" drop constraint "result_group_id_refs_id_ebdd359d";

alter table "public"."waiving_result_analyzers" drop constraint "analyzerversion_id_refs_id_24c71f8d1547f47e";

alter table "public"."waiving_result_analyzers" drop constraint "result_id_refs_id_60ed8cd82666a8cd";

alter table "public"."waiving_result_analyzers" drop constraint "waiving_result_analyzers_result_id_287bcbbfe932b2ab_uniq";

alter table "public"."waiving_resultgroup" drop constraint "waiving_resultgroup_checker_group_id_fkey";

alter table "public"."waiving_resultgroup" drop constraint "waiving_resultgroup_result_id_fkey";

alter table "public"."waiving_waiver" drop constraint "waiving_waiver_bz_id_fkey";

alter table "public"."waiving_waiver" drop constraint "waiving_waiver_result_group_id_fkey";

alter table "public"."waiving_waiver" drop constraint "waiving_waiver_user_id_fkey";

alter table "public"."waiving_waivinglog" drop constraint "user_id_refs_id_6b11541a7e64f8d1";

alter table "public"."waiving_waivinglog" drop constraint "waiver_id_refs_id_19bbee9edead3aac";

alter table "public"."auth_message" drop constraint "auth_message_pkey";

alter table "public"."south_migrationhistory" drop constraint "south_migrationhistory_pkey";

drop index if exists "public"."auth_group_permissions_group_id";

drop index if exists "public"."auth_group_permissions_group_id_key";

drop index if exists "public"."auth_group_permissions_permission_id";

drop index if exists "public"."auth_message_pkey";

drop index if exists "public"."auth_message_user_id";

drop index if exists "public"."auth_permission_content_type_id";

drop index if exists "public"."auth_permission_content_type_id_key";

drop index if exists "public"."auth_user_groups_group_id";

drop index if exists "public"."auth_user_groups_user_id";

drop index if exists "public"."auth_user_groups_user_id_key";

drop index if exists "public"."auth_user_user_permissions_permission_id";

drop index if exists "public"."auth_user_user_permissions_user_id";

drop index if exists "public"."auth_user_user_permissions_user_id_key";

drop index if exists "public"."django_admin_log_content_type_id";

drop index if exists "public"."django_admin_log_user_id";

drop index if exists "public"."django_content_type_app_label_key";

drop index if exists "public"."django_session_expire_date";

drop index if exists "public"."errata_capability_analyzers_analyzer_id";

drop index if exists "public"."errata_capability_analyzers_capability_id";

drop index if exists "public"."errata_capability_analyzers_capability_id_23cc0d877f2d97b9_uniq";

drop index if exists "public"."errata_capability_caps_capability_id";

drop index if exists "public"."errata_capability_caps_capability_id_79a5de5125845a77_uniq";

drop index if exists "public"."errata_capability_caps_packagecapability_id";

drop index if exists "public"."errata_scanningsession__scanningsession_id_ed60a3efd776a42_uniq";

drop index if exists "public"."errata_scanningsession_caps_capability_id";

drop index if exists "public"."errata_scanningsession_caps_scanningsession_id";

drop index if exists "public"."errata_scanningsession_profile_id";

drop index if exists "public"."hub_task_arch_id";

drop index if exists "public"."hub_task_channel_id";

drop index if exists "public"."hub_task_owner_id";

drop index if exists "public"."hub_task_parent_id";

drop index if exists "public"."hub_task_resubmitted_by_id";

drop index if exists "public"."hub_task_resubmitted_from_id";

drop index if exists "public"."hub_task_worker_id";

drop index if exists "public"."hub_worker_arches_arch_id";

drop index if exists "public"."hub_worker_arches_worker_id";

drop index if exists "public"."hub_worker_arches_worker_id_key";

drop index if exists "public"."hub_worker_channels_channel_id";

drop index if exists "public"."hub_worker_channels_worker_id";

drop index if exists "public"."hub_worker_channels_worker_id_key";

drop index if exists "public"."scan_analyzerversion_analyzer_id";

drop index if exists "public"."scan_analyzerversion_m_analyzerversion_id_6d8eeff244a5ca45_uniq";

drop index if exists "public"."scan_analyzerversion_mocks_analyzerversion_id";

drop index if exists "public"."scan_analyzerversion_mocks_mockconfig_id";

drop index if exists "public"."scan_clientanalyzer_analyzer_id";

drop index if exists "public"."scan_etmapping_latest_run_id";

drop index if exists "public"."scan_packageattribute_package_id";

drop index if exists "public"."scan_packageattribute_release_id";

drop index if exists "public"."scan_packagecapability_package_id";

drop index if exists "public"."scan_packagecapability_release_id";

drop index if exists "public"."scan_scan_base_id";

drop index if exists "public"."scan_scan_package_id";

drop index if exists "public"."scan_scan_parent_id";

drop index if exists "public"."scan_scan_tag_id";

drop index if exists "public"."scan_scan_username_id";

drop index if exists "public"."scan_tag_mock_id";

drop index if exists "public"."scan_tag_release_id";

drop index if exists "public"."south_migrationhistory_pkey";

drop index if exists "public"."stats_statresults_release_id";

drop index if exists "public"."stats_statresults_stat_id";

drop index if exists "public"."upload_fileupload_owner_id";

drop index if exists "public"."waiving_bugzilla_package_id";

drop index if exists "public"."waiving_bugzilla_release_id";

drop index if exists "public"."waiving_checker_group_id";

drop index if exists "public"."waiving_defect_checker_id";

drop index if exists "public"."waiving_defect_result_group_id";

drop index if exists "public"."waiving_result_analyzers_analyzerversion_id";

drop index if exists "public"."waiving_result_analyzers_result_id";

drop index if exists "public"."waiving_result_analyzers_result_id_287bcbbfe932b2ab_uniq";

drop index if exists "public"."waiving_resultgroup_checker_group_id";

drop index if exists "public"."waiving_resultgroup_result_id";

drop index if exists "public"."waiving_waiver_bz_id";

drop index if exists "public"."waiving_waiver_result_group_id";

drop index if exists "public"."waiving_waiver_user_id";

drop index if exists "public"."waiving_waivinglog_user_id";

drop index if exists "public"."waiving_waivinglog_waiver_id";

drop table "public"."auth_message";

drop table "public"."south_migrationhistory";

create table "public"."django_migrations" (
    "id" integer not null default nextval('django_migrations_id_seq'::regclass),
    "app" character varying(255) not null,
    "name" character varying(255) not null,
    "applied" timestamp with time zone not null
);


create table "public"."xmlrpc_xmlrpclog" (
    "id" integer not null default nextval('xmlrpc_xmlrpclog_id_seq'::regclass),
    "dt_inserted" timestamp with time zone not null,
    "method" character varying(255) not null,
    "args" text not null,
    "user_id" integer
);


alter table "public"."auth_group" alter column "name" set data type character varying(150) using "name"::character varying(150);

alter table "public"."auth_permission" alter column "name" set data type character varying(255) using "name"::character varying(255);

alter table "public"."auth_user" alter column "email" set data type character varying(254) using "email"::character varying(254);

alter table "public"."auth_user" alter column "last_login" drop not null;

alter table "public"."django_content_type" drop column "name";

alter table "public"."errata_capability" alter column "options" drop default;

alter table "public"."errata_scanningsession" alter column "options" drop default;

alter table "public"."hub_worker" alter column "min_priority" set not null;

alter table "public"."scan_analyzer" alter column "name" set not null;

alter table "public"."scan_clientanalyzer" drop column "name";

alter table "public"."scan_clientanalyzer" drop column "path";

alter table "public"."scan_clientanalyzer" alter column "enabled" drop default;

alter table "public"."scan_profile" alter column "command_arguments" drop default;

alter table "public"."scan_profile" alter column "enabled" drop default;

alter table "public"."scan_taskextension" alter column "secret_args" drop default;

alter sequence "public"."django_migrations_id_seq" owned by "public"."django_migrations"."id";

alter sequence "public"."xmlrpc_xmlrpclog_id_seq" owned by "public"."xmlrpc_xmlrpclog"."id";

drop sequence if exists "public"."auth_message_id_seq";

drop sequence if exists "public"."south_migrationhistory_id_seq";

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);

CREATE UNIQUE INDEX auth_group_permissions_group_id_permission_id_0cd325b0_uniq ON public.auth_group_permissions USING btree (group_id, permission_id);

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);

CREATE UNIQUE INDEX auth_permission_content_type_id_codename_01ab375a_uniq ON public.auth_permission USING btree (content_type_id, codename);

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);

CREATE UNIQUE INDEX auth_user_groups_user_id_group_id_94350c0c_uniq ON public.auth_user_groups USING btree (user_id, group_id);

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);

CREATE UNIQUE INDEX auth_user_user_permissions_user_id_permission_id_14a6b632_uniq ON public.auth_user_user_permissions USING btree (user_id, permission_id);

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);

CREATE UNIQUE INDEX django_content_type_app_label_model_76bd3d3b_uniq ON public.django_content_type USING btree (app_label, model);

CREATE UNIQUE INDEX django_migrations_pkey ON public.django_migrations USING btree (id);

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);

CREATE UNIQUE INDEX django_site_domain_a2e37b91_uniq ON public.django_site USING btree (domain);

CREATE UNIQUE INDEX errata_capability_analyz_capability_id_analyzer_i_e2859dd1_uniq ON public.errata_capability_analyzers USING btree (capability_id, analyzer_id);

CREATE INDEX errata_capability_analyzers_analyzer_id_add70073 ON public.errata_capability_analyzers USING btree (analyzer_id);

CREATE INDEX errata_capability_analyzers_capability_id_177bc82d ON public.errata_capability_analyzers USING btree (capability_id);

CREATE INDEX errata_capability_caps_capability_id_711ffd7f ON public.errata_capability_caps USING btree (capability_id);

CREATE UNIQUE INDEX errata_capability_caps_capability_id_packagecap_efcd86f1_uniq ON public.errata_capability_caps USING btree (capability_id, packagecapability_id);

CREATE INDEX errata_capability_caps_packagecapability_id_b04af3d0 ON public.errata_capability_caps USING btree (packagecapability_id);

CREATE UNIQUE INDEX errata_scanningsession_c_scanningsession_id_capab_3452995c_uniq ON public.errata_scanningsession_caps USING btree (scanningsession_id, capability_id);

CREATE INDEX errata_scanningsession_caps_capability_id_b5ebc6bd ON public.errata_scanningsession_caps USING btree (capability_id);

CREATE INDEX errata_scanningsession_caps_scanningsession_id_26846671 ON public.errata_scanningsession_caps USING btree (scanningsession_id);

CREATE INDEX errata_scanningsession_profile_id_4b2abcdb ON public.errata_scanningsession USING btree (profile_id);

CREATE INDEX hub_arch_name_3af36002_like ON public.hub_arch USING btree (name varchar_pattern_ops);

CREATE INDEX hub_arch_pretty_name_577c7071_like ON public.hub_arch USING btree (pretty_name varchar_pattern_ops);

CREATE INDEX hub_task_arch_id_732db4e5 ON public.hub_task USING btree (arch_id);

CREATE INDEX hub_task_channel_id_8a374ad4 ON public.hub_task USING btree (channel_id);

CREATE INDEX hub_task_owner_id_8c9b180c ON public.hub_task USING btree (owner_id);

CREATE INDEX hub_task_parent_id_f30b7983 ON public.hub_task USING btree (parent_id);

CREATE INDEX hub_task_resubmitted_by_id_d8fe93af ON public.hub_task USING btree (resubmitted_by_id);

CREATE INDEX hub_task_resubmitted_from_id_1ff38880 ON public.hub_task USING btree (resubmitted_from_id);

CREATE INDEX hub_task_worker_id_33da5341 ON public.hub_task USING btree (worker_id);

CREATE INDEX hub_worker_arches_arch_id_07b60aa6 ON public.hub_worker_arches USING btree (arch_id);

CREATE UNIQUE INDEX hub_worker_arches_worker_id_arch_id_b9e3dc8a_uniq ON public.hub_worker_arches USING btree (worker_id, arch_id);

CREATE INDEX hub_worker_arches_worker_id_e2e8903c ON public.hub_worker_arches USING btree (worker_id);

CREATE INDEX hub_worker_channels_channel_id_a19eb7b0 ON public.hub_worker_channels USING btree (channel_id);

CREATE INDEX hub_worker_channels_worker_id_651bfafd ON public.hub_worker_channels USING btree (worker_id);

CREATE UNIQUE INDEX hub_worker_channels_worker_id_channel_id_80e290ab_uniq ON public.hub_worker_channels USING btree (worker_id, channel_id);

CREATE INDEX hub_worker_name_3cce0b7c_like ON public.hub_worker USING btree (name varchar_pattern_ops);

CREATE INDEX hub_worker_worker_key_bae81073_like ON public.hub_worker USING btree (worker_key varchar_pattern_ops);

CREATE INDEX scan_analyzerversion_analyzer_id_003bb143 ON public.scan_analyzerversion USING btree (analyzer_id);

CREATE UNIQUE INDEX scan_analyzerversion_moc_analyzerversion_id_mockc_018f9a7b_uniq ON public.scan_analyzerversion_mocks USING btree (analyzerversion_id, mockconfig_id);

CREATE INDEX scan_analyzerversion_mocks_analyzerversion_id_c1ab96a0 ON public.scan_analyzerversion_mocks USING btree (analyzerversion_id);

CREATE INDEX scan_analyzerversion_mocks_mockconfig_id_c064aeda ON public.scan_analyzerversion_mocks USING btree (mockconfig_id);

CREATE INDEX scan_clientanalyzer_analyzer_id_67a26518 ON public.scan_clientanalyzer USING btree (analyzer_id);

CREATE INDEX scan_etmapping_latest_run_id_7013404e ON public.scan_etmapping USING btree (latest_run_id);

CREATE INDEX scan_mockconfig_name_b63d5b33_like ON public.scan_mockconfig USING btree (name varchar_pattern_ops);

CREATE INDEX scan_packageattribute_package_id_94091c3f ON public.scan_packageattribute USING btree (package_id);

CREATE INDEX scan_packageattribute_release_id_a726e272 ON public.scan_packageattribute USING btree (release_id);

CREATE INDEX scan_packagecapability_package_id_4a571cd1 ON public.scan_packagecapability USING btree (package_id);

CREATE INDEX scan_packagecapability_release_id_a81b2398 ON public.scan_packagecapability USING btree (release_id);

CREATE INDEX scan_scan_base_id_e70f9090 ON public.scan_scan USING btree (base_id);

CREATE INDEX scan_scan_package_id_299435fc ON public.scan_scan USING btree (package_id);

CREATE INDEX scan_scan_parent_id_3715997f ON public.scan_scan USING btree (parent_id);

CREATE INDEX scan_scan_tag_id_9dd043a1 ON public.scan_scan USING btree (tag_id);

CREATE INDEX scan_scan_username_id_ab609cc9 ON public.scan_scan USING btree (username_id);

CREATE INDEX scan_tag_mock_id_e1faba09 ON public.scan_tag USING btree (mock_id);

CREATE INDEX scan_tag_release_id_f1df5bce ON public.scan_tag USING btree (release_id);

CREATE INDEX stats_statresults_release_id_f3150d5a ON public.stats_statresults USING btree (release_id);

CREATE INDEX stats_statresults_stat_id_6dafe263 ON public.stats_statresults USING btree (stat_id);

CREATE INDEX upload_fileupload_owner_id_611a575b ON public.upload_fileupload USING btree (owner_id);

CREATE INDEX waiving_bugzilla_package_id_b2f4760d ON public.waiving_bugzilla USING btree (package_id);

CREATE INDEX waiving_bugzilla_release_id_f48f06d7 ON public.waiving_bugzilla USING btree (release_id);

CREATE INDEX waiving_checker_group_id_408e29a7 ON public.waiving_checker USING btree (group_id);

CREATE INDEX waiving_defect_checker_id_51a6f024 ON public.waiving_defect USING btree (checker_id);

CREATE INDEX waiving_defect_result_group_id_594a43c0 ON public.waiving_defect USING btree (result_group_id);

CREATE INDEX waiving_result_analyzers_analyzerversion_id_784bd351 ON public.waiving_result_analyzers USING btree (analyzerversion_id);

CREATE INDEX waiving_result_analyzers_result_id_8fdb1df2 ON public.waiving_result_analyzers USING btree (result_id);

CREATE UNIQUE INDEX waiving_result_analyzers_result_id_analyzerversio_654d4fa7_uniq ON public.waiving_result_analyzers USING btree (result_id, analyzerversion_id);

CREATE INDEX waiving_resultgroup_checker_group_id_bfbdbcc5 ON public.waiving_resultgroup USING btree (checker_group_id);

CREATE INDEX waiving_resultgroup_result_id_cf7f10b5 ON public.waiving_resultgroup USING btree (result_id);

CREATE INDEX waiving_waiver_bz_id_f8ed8731 ON public.waiving_waiver USING btree (bz_id);

CREATE INDEX waiving_waiver_result_group_id_7a3a3230 ON public.waiving_waiver USING btree (result_group_id);

CREATE INDEX waiving_waiver_user_id_8d53fce8 ON public.waiving_waiver USING btree (user_id);

CREATE INDEX waiving_waivinglog_user_id_2204a207 ON public.waiving_waivinglog USING btree (user_id);

CREATE INDEX waiving_waivinglog_waiver_id_2b006f1c ON public.waiving_waivinglog USING btree (waiver_id);

CREATE UNIQUE INDEX xmlrpc_xmlrpclog_pkey ON public.xmlrpc_xmlrpclog USING btree (id);

CREATE INDEX xmlrpc_xmlrpclog_user_id_6192e9ec ON public.xmlrpc_xmlrpclog USING btree (user_id);

alter table "public"."django_migrations" add constraint "django_migrations_pkey" PRIMARY KEY using index "django_migrations_pkey";

alter table "public"."xmlrpc_xmlrpclog" add constraint "xmlrpc_xmlrpclog_pkey" PRIMARY KEY using index "xmlrpc_xmlrpclog_pkey";

alter table "public"."auth_group_permissions" add constraint "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY (permission_id) REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."auth_group_permissions" add constraint "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY (group_id) REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."auth_group_permissions" add constraint "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE using index "auth_group_permissions_group_id_permission_id_0cd325b0_uniq";

alter table "public"."auth_permission" add constraint "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."auth_permission" add constraint "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE using index "auth_permission_content_type_id_codename_01ab375a_uniq";

alter table "public"."auth_user_groups" add constraint "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY (group_id) REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."auth_user_groups" add constraint "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."auth_user_groups" add constraint "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE using index "auth_user_groups_user_id_group_id_94350c0c_uniq";

alter table "public"."auth_user_user_permissions" add constraint "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY (permission_id) REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."auth_user_user_permissions" add constraint "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."auth_user_user_permissions" add constraint "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE using index "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq";

alter table "public"."django_admin_log" add constraint "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."django_admin_log" add constraint "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."django_content_type" add constraint "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE using index "django_content_type_app_label_model_76bd3d3b_uniq";

alter table "public"."django_site" add constraint "django_site_domain_a2e37b91_uniq" UNIQUE using index "django_site_domain_a2e37b91_uniq";

alter table "public"."errata_capability_analyzers" add constraint "errata_capability_an_analyzer_id_add70073_fk_scan_anal" FOREIGN KEY (analyzer_id) REFERENCES scan_analyzer(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."errata_capability_analyzers" add constraint "errata_capability_an_capability_id_177bc82d_fk_errata_ca" FOREIGN KEY (capability_id) REFERENCES errata_capability(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."errata_capability_analyzers" add constraint "errata_capability_analyz_capability_id_analyzer_i_e2859dd1_uniq" UNIQUE using index "errata_capability_analyz_capability_id_analyzer_i_e2859dd1_uniq";

alter table "public"."errata_capability_caps" add constraint "errata_capability_ca_capability_id_711ffd7f_fk_errata_ca" FOREIGN KEY (capability_id) REFERENCES errata_capability(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."errata_capability_caps" add constraint "errata_capability_ca_packagecapability_id_b04af3d0_fk_scan_pack" FOREIGN KEY (packagecapability_id) REFERENCES scan_packagecapability(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."errata_capability_caps" add constraint "errata_capability_caps_capability_id_packagecap_efcd86f1_uniq" UNIQUE using index "errata_capability_caps_capability_id_packagecap_efcd86f1_uniq";

alter table "public"."errata_scanningsession" add constraint "errata_scanningsession_profile_id_4b2abcdb_fk_scan_profile_id" FOREIGN KEY (profile_id) REFERENCES scan_profile(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."errata_scanningsession_caps" add constraint "errata_scanningsessi_capability_id_b5ebc6bd_fk_errata_ca" FOREIGN KEY (capability_id) REFERENCES errata_capability(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."errata_scanningsession_caps" add constraint "errata_scanningsessi_scanningsession_id_26846671_fk_errata_sc" FOREIGN KEY (scanningsession_id) REFERENCES errata_scanningsession(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."errata_scanningsession_caps" add constraint "errata_scanningsession_c_scanningsession_id_capab_3452995c_uniq" UNIQUE using index "errata_scanningsession_c_scanningsession_id_capab_3452995c_uniq";

alter table "public"."hub_task" add constraint "hub_task_arch_id_732db4e5_fk_hub_arch_id" FOREIGN KEY (arch_id) REFERENCES hub_arch(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."hub_task" add constraint "hub_task_channel_id_8a374ad4_fk_hub_channel_id" FOREIGN KEY (channel_id) REFERENCES hub_channel(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."hub_task" add constraint "hub_task_owner_id_8c9b180c_fk_auth_user_id" FOREIGN KEY (owner_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."hub_task" add constraint "hub_task_parent_id_f30b7983_fk_hub_task_id" FOREIGN KEY (parent_id) REFERENCES hub_task(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."hub_task" add constraint "hub_task_resubmitted_by_id_d8fe93af_fk_auth_user_id" FOREIGN KEY (resubmitted_by_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."hub_task" add constraint "hub_task_resubmitted_from_id_1ff38880_fk_hub_task_id" FOREIGN KEY (resubmitted_from_id) REFERENCES hub_task(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."hub_task" add constraint "hub_task_worker_id_33da5341_fk_hub_worker_id" FOREIGN KEY (worker_id) REFERENCES hub_worker(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."hub_worker_arches" add constraint "hub_worker_arches_arch_id_07b60aa6_fk_hub_arch_id" FOREIGN KEY (arch_id) REFERENCES hub_arch(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."hub_worker_arches" add constraint "hub_worker_arches_worker_id_arch_id_b9e3dc8a_uniq" UNIQUE using index "hub_worker_arches_worker_id_arch_id_b9e3dc8a_uniq";

alter table "public"."hub_worker_arches" add constraint "hub_worker_arches_worker_id_e2e8903c_fk_hub_worker_id" FOREIGN KEY (worker_id) REFERENCES hub_worker(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."hub_worker_channels" add constraint "hub_worker_channels_channel_id_a19eb7b0_fk_hub_channel_id" FOREIGN KEY (channel_id) REFERENCES hub_channel(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."hub_worker_channels" add constraint "hub_worker_channels_worker_id_651bfafd_fk_hub_worker_id" FOREIGN KEY (worker_id) REFERENCES hub_worker(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."hub_worker_channels" add constraint "hub_worker_channels_worker_id_channel_id_80e290ab_uniq" UNIQUE using index "hub_worker_channels_worker_id_channel_id_80e290ab_uniq";

alter table "public"."scan_analyzerversion" add constraint "scan_analyzerversion_analyzer_id_003bb143_fk_scan_analyzer_id" FOREIGN KEY (analyzer_id) REFERENCES scan_analyzer(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_analyzerversion_mocks" add constraint "scan_analyzerversion_analyzerversion_id_c1ab96a0_fk_scan_anal" FOREIGN KEY (analyzerversion_id) REFERENCES scan_analyzerversion(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_analyzerversion_mocks" add constraint "scan_analyzerversion_moc_analyzerversion_id_mockc_018f9a7b_uniq" UNIQUE using index "scan_analyzerversion_moc_analyzerversion_id_mockc_018f9a7b_uniq";

alter table "public"."scan_analyzerversion_mocks" add constraint "scan_analyzerversion_mockconfig_id_c064aeda_fk_scan_mock" FOREIGN KEY (mockconfig_id) REFERENCES scan_mockconfig(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_clientanalyzer" add constraint "scan_clientanalyzer_analyzer_id_67a26518_fk_scan_analyzer_id" FOREIGN KEY (analyzer_id) REFERENCES scan_analyzer(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_etmapping" add constraint "scan_etmapping_latest_run_id_7013404e_fk_scan_scanbinding_id" FOREIGN KEY (latest_run_id) REFERENCES scan_scanbinding(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_packageattribute" add constraint "scan_packageattribut_release_id_a726e272_fk_scan_syst" FOREIGN KEY (release_id) REFERENCES scan_systemrelease(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_packageattribute" add constraint "scan_packageattribute_package_id_94091c3f_fk_scan_package_id" FOREIGN KEY (package_id) REFERENCES scan_package(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_packagecapability" add constraint "scan_packagecapabili_release_id_a81b2398_fk_scan_syst" FOREIGN KEY (release_id) REFERENCES scan_systemrelease(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_packagecapability" add constraint "scan_packagecapability_package_id_4a571cd1_fk_scan_package_id" FOREIGN KEY (package_id) REFERENCES scan_package(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_scan" add constraint "scan_scan_base_id_e70f9090_fk_scan_scan_id" FOREIGN KEY (base_id) REFERENCES scan_scan(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_scan" add constraint "scan_scan_package_id_299435fc_fk_scan_package_id" FOREIGN KEY (package_id) REFERENCES scan_package(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_scan" add constraint "scan_scan_parent_id_3715997f_fk_scan_scan_id" FOREIGN KEY (parent_id) REFERENCES scan_scan(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_scan" add constraint "scan_scan_tag_id_9dd043a1_fk_scan_tag_id" FOREIGN KEY (tag_id) REFERENCES scan_tag(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_scan" add constraint "scan_scan_username_id_ab609cc9_fk_auth_user_id" FOREIGN KEY (username_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_scanbinding" add constraint "scan_scanbinding_result_id_e4b9a64d_fk_waiving_result_id" FOREIGN KEY (result_id) REFERENCES waiving_result(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_scanbinding" add constraint "scan_scanbinding_scan_id_58c2198e_fk_scan_scan_id" FOREIGN KEY (scan_id) REFERENCES scan_scan(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_scanbinding" add constraint "scan_scanbinding_task_id_ab3fc4f2_fk_hub_task_id" FOREIGN KEY (task_id) REFERENCES hub_task(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_systemrelease" add constraint "scan_systemrelease_parent_id_d400b7b6_fk_scan_systemrelease_id" FOREIGN KEY (parent_id) REFERENCES scan_systemrelease(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_tag" add constraint "scan_tag_mock_id_e1faba09_fk_scan_mockconfig_id" FOREIGN KEY (mock_id) REFERENCES scan_mockconfig(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_tag" add constraint "scan_tag_release_id_f1df5bce_fk_scan_systemrelease_id" FOREIGN KEY (release_id) REFERENCES scan_systemrelease(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."scan_taskextension" add constraint "scan_taskextension_task_id_274754b0_fk_hub_task_id" FOREIGN KEY (task_id) REFERENCES hub_task(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."stats_statresults" add constraint "stats_statresults_release_id_f3150d5a_fk_scan_systemrelease_id" FOREIGN KEY (release_id) REFERENCES scan_systemrelease(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."stats_statresults" add constraint "stats_statresults_stat_id_6dafe263_fk_stats_stattype_id" FOREIGN KEY (stat_id) REFERENCES stats_stattype(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."upload_fileupload" add constraint "upload_fileupload_owner_id_611a575b_fk_auth_user_id" FOREIGN KEY (owner_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."waiving_bugzilla" add constraint "waiving_bugzilla_package_id_b2f4760d_fk_scan_package_id" FOREIGN KEY (package_id) REFERENCES scan_package(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."waiving_bugzilla" add constraint "waiving_bugzilla_release_id_f48f06d7_fk_scan_systemrelease_id" FOREIGN KEY (release_id) REFERENCES scan_systemrelease(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."waiving_checker" add constraint "waiving_checker_group_id_408e29a7_fk_waiving_checkergroup_id" FOREIGN KEY (group_id) REFERENCES waiving_checkergroup(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."waiving_defect" add constraint "waiving_defect_checker_id_51a6f024_fk_waiving_checker_id" FOREIGN KEY (checker_id) REFERENCES waiving_checker(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."waiving_defect" add constraint "waiving_defect_result_group_id_594a43c0_fk_waiving_r" FOREIGN KEY (result_group_id) REFERENCES waiving_resultgroup(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."waiving_result_analyzers" add constraint "waiving_result_analy_analyzerversion_id_784bd351_fk_scan_anal" FOREIGN KEY (analyzerversion_id) REFERENCES scan_analyzerversion(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."waiving_result_analyzers" add constraint "waiving_result_analy_result_id_8fdb1df2_fk_waiving_r" FOREIGN KEY (result_id) REFERENCES waiving_result(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."waiving_result_analyzers" add constraint "waiving_result_analyzers_result_id_analyzerversio_654d4fa7_uniq" UNIQUE using index "waiving_result_analyzers_result_id_analyzerversio_654d4fa7_uniq";

alter table "public"."waiving_resultgroup" add constraint "waiving_resultgroup_checker_group_id_bfbdbcc5_fk_waiving_c" FOREIGN KEY (checker_group_id) REFERENCES waiving_checkergroup(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."waiving_resultgroup" add constraint "waiving_resultgroup_result_id_cf7f10b5_fk_waiving_result_id" FOREIGN KEY (result_id) REFERENCES waiving_result(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."waiving_waiver" add constraint "waiving_waiver_bz_id_f8ed8731_fk_waiving_bugzilla_id" FOREIGN KEY (bz_id) REFERENCES waiving_bugzilla(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."waiving_waiver" add constraint "waiving_waiver_result_group_id_7a3a3230_fk_waiving_r" FOREIGN KEY (result_group_id) REFERENCES waiving_resultgroup(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."waiving_waiver" add constraint "waiving_waiver_user_id_8d53fce8_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."waiving_waivinglog" add constraint "waiving_waivinglog_user_id_2204a207_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."waiving_waivinglog" add constraint "waiving_waivinglog_waiver_id_2b006f1c_fk_waiving_waiver_id" FOREIGN KEY (waiver_id) REFERENCES waiving_waiver(id) DEFERRABLE INITIALLY DEFERRED;

alter table "public"."xmlrpc_xmlrpclog" add constraint "xmlrpc_xmlrpclog_user_id_6192e9ec_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;
