# Generated by Django 2.2.24 on 2023-04-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0002_auto_20190611_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanningsession',
            name='caps',
        ),
        migrations.DeleteModel(
            name='Capability',
        ),
    ]
