# Generated by Django 3.2.18 on 2023-05-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0003_auto_20230403_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanningsession',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
