#!/usr/bin/python3

import sys

import kobo.exceptions
import kobo.conf
import kobo.worker.main
import kobo.worker.tasks

# assuming all tasks are in covscand/tasks/task_*.py modules
import covscand.tasks
from covscancommon.utils.conf import get_config_dict


def main():
    # register generic kobo tasks
    kobo.worker.main.TaskContainer.register_module(kobo.worker.tasks, prefix="task_")
    # register project specific tasks
    kobo.worker.main.TaskContainer.register_module(covscand.tasks, prefix="task_")

    # configuration
    conf = get_config_dict(config_env="COVSCAND_CONFIG_FILE", config_default="/etc/covscan/covscand.conf")
    if conf is None:
        return 2

    try:
        kobo.worker.main.main(conf)
    except KeyboardInterrupt:
        sys.stderr.write("\n\nExiting on user cancel.\n")
        return 1
    except kobo.exceptions.ImproperlyConfigured as ex:
        sys.stderr.write("\n\nImproperly configured: %s\n" % ex)
        return 3
    except IOError as ex:
        sys.stderr.write("\n\nIO Error: %s\n" % ex)
        return 4


if __name__ == "__main__":
    sys.exit(main())
