# Generated by Django 2.2.24 on 2022-07-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_auto_20211223_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzerversion',
            name='mocks',
            field=models.ManyToManyField(blank=True, related_name='analyzers', to='scan.MockConfig'),
        ),
    ]
