# Generated by Django 2.2.24 on 2023-01-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0004_auto_20220714_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='priority_offset',
            field=models.SmallIntegerField(default=0, help_text='Set this to alter priority of this packages scan'),
        ),
    ]
