# Generated by Django 2.2.24 on 2023-04-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errata', '0003_auto_20230403_1830'),
        ('scan', '0006_auto_20230329_1348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageCapability',
        ),
    ]
