# Generated by Django 2.2.24 on 2023-04-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0007_delete_packagecapability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='eligible',
        ),
    ]
