# Generated by Django 3.2.18 on 2023-04-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0008_remove_package_eligible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskExtension',
        ),
    ]
