# Generated by Django 2.2.24 on 2023-04-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0009_delete_taskextension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientanalyzer',
            name='cli_short_command',
        ),
    ]
