# Generated by Django 4.0.2 on 2023-04-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0010_remove_clientanalyzer_cli_short_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etmapping',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=384),
        ),
    ]
