# Generated by Django 3.2.18 on 2023-05-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0012_alter_package_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='command_arguments',
            field=models.JSONField(default=dict, help_text="this field has to contain key 'analyzers', which is a comma separated list of analyzers, optionally add key csmock_args, which is a string"),
        ),
    ]
