# Generated by Django 3.2.20 on 2023-11-13 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_alter_task_worker'),
        ('scan', '0017_auto_20231102_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionPolicySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128)),
                ('days', models.PositiveIntegerField(default=30, help_text='Number of days before the task is deleted.')),
            ],
        ),
        migrations.CreateModel(
            name='TaskResultsRemoval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_retention_applied', models.DateTimeField(auto_now_add=True)),
                ('reason', models.ForeignKey(help_text='Reason why the retention was applied to the task', on_delete=django.db.models.deletion.CASCADE, to='scan.retentionpolicysetting')),
                ('task', models.ForeignKey(help_text='Task with the retention policy applied', on_delete=django.db.models.deletion.CASCADE, to='hub.task')),
            ],
        ),
    ]
