# Generated by Django 3.2.20 on 2024-03-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0018_retentionpolicysetting_taskresultsremoval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyzer',
            options={'ordering': ['name']},
        ),
    ]
