# Generated by Django 3.2.18 on 2023-05-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiving', '0004_auto_20230403_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='events',
            field=models.JSONField(default=list, help_text='List of defect related events.'),
        ),
    ]
