# Generated by Django 3.2.20 on 2023-11-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiving', '0006_fix_jirabug_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checker',
            name='severity',
        ),
    ]
