# Generated by Django 3.2.20 on 2024-01-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiving', '0007_remove_checker_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultgroup',
            name='defects_count',
        ),
    ]
