---
name: Coverity

on:
  push:
    branches: [main]

jobs:
  coverity:
    if: github.repository == 'openscanhub/openscanhub'
    name: Coverity Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Coverity scan
        uses: vapier/coverity-scan-action@v1
        with:
          build_language: other  # other is for Python, etc...
          email: ${{ secrets.COVERITY_SCAN_EMAIL }}
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
          project: openscanhub/openscanhub
          command: --no-command --fs-capture-search ./osh
